[package]
name = "rucy-mruby-prelude"
version = "0.1.0"
authors = ["Uchio Kondo <udzura@udzura.jp>"]
edition = "2018"

[dependencies]
mrusty = { git = 'https://github.com/udzura/mrusty.git' }
# mrusty = { path = '../../mrusty' }
